[package]
name = "astria-sequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
bytes = "1.4"
is-terminal = "0.4.7"
penumbra-component = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.52.2" }
penumbra-storage = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.52.2" }
tendermint-proto = "0.29"
tendermint = "0.29"
tower = "0.4"
tower-abci = "0.5.0"
tower-actor = "0.1.0"
tokio-util = "0.7.8"

color-eyre = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["derive"]  }
serde_json = { workspace = true }
tokio = { workspace = true, features = [ "tracing" ] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["ansi", "env-filter", "json"] }

[dev-dependencies]
prost = { workspace = true }
