[package]
name = "astria-conductor"
version = "0.4.0"
edition = "2021"
rust-version = "1.70.0"

[dependencies]
sync_wrapper = "0.1.2"

async-trait = { workspace = true }
base64 = { workspace = true }
color-eyre = { workspace = true }
ed25519-consensus = { workspace = true }
figment = { workspace = true, features = ["env"] }
futures = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
telemetry = { package = "astria-telemetry", path = "../astria-telemetry" }
tendermint = { workspace = true }
tendermint-rpc = { workspace = true }
tendermint-proto = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tonic = { workspace = true }
tracing = { workspace = true }

astria-proto = { path = "../astria-proto", features = ["client"] }
sequencer-client = { package = "astria-sequencer-client", path = "../astria-sequencer-client", features = [
  "http",
  "websocket",
] }
astria-sequencer-relayer = { path = "../astria-sequencer-relayer" }
astria-sequencer-types = { path = "../astria-sequencer-types" }
sequencer-validation = { package = "astria-sequencer-validation", path = "../astria-sequencer-validation" }


[dev-dependencies]
astria-proto = { path = "../astria-proto", features = ["client", "server"] }
once_cell = { workspace = true }
figment = { workspace = true, features = ["test"] }
regex = { workspace = true }
astria-celestia-jsonrpc-client = { path = "../astria-celestia-jsonrpc-client", features = [
  "server",
] }

ethers = { version = "2.0.7", features = ["ws"] }
impl-serde = "0.4.0"
jsonrpsee = { workspace = true, features = ["macros", "server"] }
rand = { workspace = true }
