[package]
name = "astria-conductor"
version = "0.11.0"
edition = "2021"
rust-version = "1.73"

[dependencies]
async-trait = "0.1.73"

base64 = { workspace = true }
color-eyre = { workspace = true }
deadpool = { version = "0.10.0", default-features = false, features = [
  "managed",
] }
ed25519-consensus = { workspace = true }
ethers = { workspace = true, features = ["optimism", "ws"] }
futures = { workspace = true }
hex = { workspace = true }
humantime = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tendermint = { workspace = true }
tendermint-proto = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tokio-util = { workspace = true, features = ["rt"] }
tonic = { workspace = true }
tracing = { workspace = true }
tryhard = { workspace = true }

celestia-client = { package = "astria-celestia-client", path = "../celestia-client" }
sequencer-types = { package = "astria-sequencer-types", path = "../sequencer-types" }
optimism = { package = "astria-optimism", path = "../optimism" }
config = { package = "astria-config", path = "../config" }
merkle = { package = "astria-merkle", path = "../merkle" }
proto = { package = "astria-proto", path = "../proto", features = ["client"] }
sequencer-client = { package = "astria-sequencer-client", path = "../sequencer-client", features = [
  "websocket",
] }
telemetry = { package = "astria-telemetry", path = "../telemetry" }

[dev-dependencies]
jsonrpsee = { workspace = true, features = ["server"] }

sequencer-types = { package = "astria-sequencer-types", path = "../sequencer-types", features = [
  "test-utils",
] }
optimism = { package = "astria-optimism", path = "../optimism", features = [
  "test-utils",
] }
config = { package = "astria-config", path = "../config", features = ["tests"] }
proto = { package = "astria-proto", path = "../proto", features = ["server"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
