name: Docker

# Trigger on pushes to master branch, new semantic version tags, and pull request updates
on:
  workflow_dispatch:
  push:
    branches:
      - "sequencer-v0.7.x"
    tags:
      - "sequencer-v0.7.[0-9]+--[a-z]+**"
  # trigger on pull request updates when target is `main` branch
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - "sequencer-v0.7.x"

jobs:
  run_checker:
    uses: ./.github/workflows/reusable-run-checker.yml

  sequencer:
    needs: run_checker
    if: needs.run_checker.outputs.run_docker == 'true'
    uses: './.github/workflows/reusable-docker-build.yml'
    with:
      package-name: sequencer
      target-binary: astria-sequencer
    secrets: inherit

  docker:
    if: ${{ always() && !cancelled() }}
    needs: [sequencer]
    uses: ./.github/workflows/reusable-success.yml
    with:
      success: ${{ !contains(needs.*.result, 'failure') }}
