name: Release
on:
  pull_request:
  push:
    branches:
      - "sequencer-v0.7.x"

jobs:
  run_checker:
    uses: ./.github/workflows/reusable-run-checker.yml
  
  sequencer:
    needs: run_checker
    if: needs.run_checker.outputs.run_release_services == 'true'
    uses: ./.github/workflows/reusable-cargo-version.yml
    with:
      package-name: 'sequencer'
      display-name: 'Sequencer'

  release:
    needs: [sequencer]
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/reusable-success.yml
    with:
      success: ${{ !contains(needs.*.result, 'failure') }}
